name: Run Tests
on:
  pull_request:
    branches: [main]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all tests.
        run: ./scripts/run-tests.sh

