name: Gated Run Tests
on:
  workflow_run:
    workflows:
      - gated-workflow
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all tests.
        run: ./scripts/run-tests.sh

