name: Skip Behaviors

on:
  workflow_dispatch: {}

env:
  SKIP: 'true'

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - run: echo "::warning::one"
  two:
    if: env.SKIP != 'true'
    runs-on: ubuntu-latest
    steps:
    - run: echo "::warning::two"
  three:
    needs: [two]
    runs-on: ubuntu-latest
    steps:
    - run: echo "::warning::three"
  four:
    needs: [three]
    runs-on: ubuntu-latest
    steps:
    - run: echo "::warning::four"
