name: Arbitrary action on tag creation
on:  
  create:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get tag reference
        run: |
          echo RELEASE_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3) >> $GITHUB_ENV
          
      - name: Confirm tag reference in later task
        run: |
          echo $RELEASE_TAG
